### ISSUE TITLE
running "python setup.py install", but failed

### ISSUE THREAD

**Issue by handsomeli1898** [dvlab-research/SparseTransformer#9]
The errors are as follow:

Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    setup(
  File "/home/pufan_li/.conda/envs/vis_spray/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "/home/pufan_li/.conda/envs/vis_spray/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/pufan_li/.conda/envs/vis_spray/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/pufan_li/.conda/envs/vis_spray/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/pufan_li/.conda/envs/vis_spray/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/pufan_li/.conda/envs/vis_spray/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/pufan_li/.conda/envs/vis_spray/lib/python3.8/site-packages/setuptools/command/install.py", line 84, in run
    self.do_egg_install()
  File "/home/pufan_li/.conda/envs/vis_spray/lib/python3.8/site-packages/setuptools/command/install.py", line 132, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/pufan_li/.conda/envs/vis_spray/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/pufan_li/.conda/envs/vis_spray/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/pufan_li/.conda/envs/vis_spray/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/pufan_li/.conda/envs/vis_spray/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/pufan_li/.conda/envs/vis_spray/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "/home/pufan_li/.conda/envs/vis_spray/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/pufan_li/.conda/envs/vis_spray/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/pufan_li/.conda/envs/vis_spray/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/pufan_li/.conda/envs/vis_spray/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/pufan_li/.conda/envs/vis_spray/lib/python3.8/site-packages/setuptools/_distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/home/pufan_li/.conda/envs/vis_spray/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/pufan_li/.conda/envs/vis_spray/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/pufan_li/.conda/envs/vis_spray/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/pufan_li/.conda/envs/vis_spray/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 88, in run
    _build_ext.run(self)
  File "/home/pufan_li/.conda/envs/vis_spray/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/home/pufan_li/.conda/envs/vis_spray/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 765, in build_extensions
    build_ext.build_extensions(self)
  File "/home/pufan_li/.conda/envs/vis_spray/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/home/pufan_li/.conda/envs/vis_spray/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/pufan_li/.conda/envs/vis_spray/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/pufan_li/.conda/envs/vis_spray/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
  File "/home/pufan_li/.conda/envs/vis_spray/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 586, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/pufan_li/.conda/envs/vis_spray/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1487, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/pufan_li/.conda/envs/vis_spray/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1824, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

Anyone know how to solve the problem?

**Comment by xiaosa269** [comment]
Hello, I have also encountered this issue. Have you resolved it? Could you please share the solution if you have one?

**Comment by handsomeli1898** [comment]
> Hello, I have also encountered this issue. Have you resolved it? Could you please share the solution if you have one?

Torch version not exceeding 1.9.0
or
Replace <THC/THC.h> with <ATen/ATen.h>

**Comment by xiaosa269** [comment]
thank you
